name: Wheels

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    uses: ./.github/workflows/wheels-macos.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "macos-wheels"

  linux:
    uses: ./.github/workflows/wheels-linux.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "manylinux-wheels"

  windows:
    uses: ./.github/workflows/wheels-windows.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "windows-wheels"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [macos, linux, windows]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-wheels-*.zip"
          merge-multiple: true
      - name: Upload Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    needs: [macos, linux, windows]
    runs-on: ubuntu-latest
    name: Wheels Successful
    steps:
      - name: Success
        run: echo Wheels Successful
