name: Build Windows wheels

on:
  workflow_call:
    inputs:
      build-commit:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

env:
  REPO_DIR: nipy

jobs:
  build:
    name: ${{ matrix.python }}
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        python: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
    env:
      BUILD_COMMIT: ${{ inputs.build-commit }}
      WHEEL_SDIR: wheelhouse
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Set Numpy version
        run: |
          $np_dep = python .\get_numpy_version.py ${{ matrix.python }}
          echo "BUILD_DEPENDS=$np_dep" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Build Wheel
        run: .github/workflows/build.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: wheelhouse/*.whl
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
